SET search_path = unc_249695;

DROP TABLE IF EXISTS gr05_patrocinios CASCADE;
DROP TABLE IF EXISTS gr05_patrocinante CASCADE;
DROP TABLE IF EXISTS gr05_evento_edicion CASCADE;
DROP TABLE IF EXISTS gr05_evento CASCADE;
DROP TABLE IF EXISTS gr05_distrito CASCADE;
DROP TABLE IF EXISTS gr05_provincia CASCADE;
DROP TABLE IF EXISTS gr05_pais CASCADE;
DROP TABLE IF EXISTS gr05_usuario CASCADE;
DROP TABLE IF EXISTS gr05_subcategoria CASCADE;
DROP TABLE IF EXISTS gr05_categoria CASCADE;
